### ISSUE TITLE
Ideas

### ISSUE THREAD

**Issue by CristianGorrin** [CristianGorrin/web_pba_2_semester_project#2]
We want to see an idea that fulfills the requirements from the description on fronter. 
- [x] PHP prototype
- [x] Wireframes prototype
- [x] Designs

**Comment by fskjeldsen** [comment]
General ideas from our talks on day 1: [link](https://github.com/CristianGorrin/web_pba_2_semester_project/wiki/General-ideas)

**Comment by CristianGorrin** [comment]
[See wireframes her](https://github.com/CristianGorrin/web_pba_2_semester_project/tree/master/_items/prototypes/wireframe)
